// <auto-generated />
using System;
using ConectaStore.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConectaStore.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260622171937_teste")]
    partial class teste
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConectaStore.API.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cor")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<string>("Foto")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cor = "#FF5733",
                            Nome = "Smartphones"
                        },
                        new
                        {
                            Id = 2,
                            Cor = "#33FF57",
                            Nome = "Notebooks"
                        },
                        new
                        {
                            Id = 3,
                            Cor = "#3357FF",
                            Nome = "SmartWatches"
                        },
                        new
                        {
                            Id = 4,
                            Cor = "#FF33A1",
                            Nome = "Fones de Ouvido"
                        },
                        new
                        {
                            Id = 5,
                            Cor = "#A855F7",
                            Nome = "Tablets"
                        },
                        new
                        {
                            Id = 6,
                            Cor = "#F59E0B",
                            Nome = "Acessórios"
                        },
                        new
                        {
                            Id = 7,
                            Cor = "#10B981",
                            Nome = "Gaming"
                        },
                        new
                        {
                            Id = 8,
                            Cor = "#EC4899",
                            Nome = "Áudio"
                        });
                });

            modelBuilder.Entity("ConectaStore.API.Models.ItemVenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("VendaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("VendaId");

                    b.ToTable("ItensVenda");
                });

            modelBuilder.Entity("ConectaStore.API.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<bool>("Destaque")
                        .HasColumnType("bit");

                    b.Property<string>("Foto")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Qtde")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorCusto")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("ValorVenda")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Descricao = "O iPhone 17 Pro é o mais recente lançamento da Apple, trazendo um design elegante e recursos avançados. Com uma tela Super Retina XDR de 6,1 polegadas, o dispositivo oferece uma experiência visual imersiva. Equipado com o chip A17 Bionic, o iPhone 17 Pro proporciona desempenho excepcional e eficiência energética. O sistema de câmera tripla inclui uma lente principal de 12 MP, uma lente ultra-angular de 12 MP e uma lente telefoto de 12 MP, permitindo fotos e vídeos de alta qualidade.",
                            Destaque = true,
                            Foto = "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-17-pro-gold-select?wid=940&hei=1112&fmt=png-alpha&.v=1700792800",
                            Nome = "iPhone 17 Pro",
                            Qtde = 5,
                            ValorCusto = 1000m,
                            ValorVenda = 10000.50m
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            Descricao = "O MacBook Air é o notebook mais leve e portátil da Apple. Com o chip M2, oferece desempenho excepcional e eficiência energética. A tela Retina de 13,6 polegadas proporciona uma experiência visual imersiva. Até 18 horas de autonomia.",
                            Destaque = true,
                            Foto = "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/macbook-air-m2-select?wid=940&hei=1112&fmt=png-alpha&.v=1700792800",
                            Nome = "MacBook Air M2",
                            Qtde = 3,
                            ValorCusto = 2000m,
                            ValorVenda = 20000.99m
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 3,
                            Descricao = "Smartwatch mais avançado da Apple. Tela Retina sempre ativa, monitoramento de frequência cardíaca, rastreamento de atividades, detecção de quedas. Resistente à água.",
                            Destaque = true,
                            Foto = "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/apple-watch-series-9-gps-select?wid=940&hei=1112&fmt=png-alpha&.v=1700792800",
                            Nome = "Apple Watch Series 9",
                            Qtde = 8,
                            ValorCusto = 300m,
                            ValorVenda = 2500.00m
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 4,
                            Descricao = "Fones de ouvido sem fio premium com cancelamento ativo de ruído, modo transparência, resistentes à água e suor. Carregamento sem fio incluso.",
                            Destaque = true,
                            Foto = "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MWP22?wid=940&hei=1112&fmt=png-alpha&.v=1700792800",
                            Nome = "AirPods Pro 2",
                            Qtde = 12,
                            ValorCusto = 700m,
                            ValorVenda = 5600.00m
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 5,
                            Descricao = "Tablet premium com tela Dynamic AMOLED 2X de 11 polegadas, processador Snapdragon 8 Gen 2, caneta S-PEN inclusa, resistência à água IP68.",
                            Destaque = true,
                            Foto = "https://images.samsung.com/is/image/samsung/p6p-br/galaxy-tab-s9/bu_tab_s9_lunar_silver.jpg",
                            Nome = "Samsung Galaxy Tab S9",
                            Qtde = 6,
                            ValorCusto = 1800m,
                            ValorVenda = 8500.00m
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 5,
                            Descricao = "iPad Air com chip M2, tela Liquid Retina de 11 polegadas, compatível com Apple Pencil e Magic Keyboard. Ideal para produtividade e criatividade.",
                            Destaque = false,
                            Foto = "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/ipad-air-m2-select?wid=940&hei=1112&fmt=png-alpha&.v=1700792800",
                            Nome = "iPad Air M2",
                            Qtde = 4,
                            ValorCusto = 2200m,
                            ValorVenda = 9200.00m
                        },
                        new
                        {
                            Id = 7,
                            CategoriaId = 6,
                            Descricao = "Carregador USB-C PD 65W compacto, compatível com notebooks e smartphones. Carregamento rápido GaN, proteção contra sobrecarga.",
                            Destaque = false,
                            Foto = "https://m.media-amazon.com/images/I/51L3tG7tJTL._AC_SX679_.jpg",
                            Nome = "Carregador Turbo 65W",
                            Qtde = 25,
                            ValorCusto = 45m,
                            ValorVenda = 189.90m
                        },
                        new
                        {
                            Id = 8,
                            CategoriaId = 6,
                            Descricao = "Capa protetora universal para notebooks de até 15.6 polegadas. Material resistente a impactos, interior acolchoado, alça de transporte.",
                            Destaque = false,
                            Foto = "https://m.media-amazon.com/images/I/71b8J1fVqOL._AC_SX679_.jpg",
                            Nome = "Capa para Notebook 15\"",
                            Qtde = 18,
                            ValorCusto = 35m,
                            ValorVenda = 149.90m
                        },
                        new
                        {
                            Id = 9,
                            CategoriaId = 7,
                            Descricao = "Mouse gamer com sensor óptico de 16000 DPI, 8 botões programáveis, iluminação RGB personalizável, cabo trançado USB.",
                            Destaque = true,
                            Foto = "https://m.media-amazon.com/images/I/61Hn4TCjtDL._AC_SX679_.jpg",
                            Nome = "Mouse Gamer RGB",
                            Qtde = 15,
                            ValorCusto = 60m,
                            ValorVenda = 249.90m
                        },
                        new
                        {
                            Id = 10,
                            CategoriaId = 7,
                            Descricao = "Teclado mecânico RGB com switches azuis, estrutura em alumínio, teclas PBT double-shot, anti-ghosting, USB-C destacável.",
                            Destaque = false,
                            Foto = "https://m.media-amazon.com/images/I/71b8J1fVqOL._AC_SX679_.jpg",
                            Nome = "Teclado Mecânico Gamer",
                            Qtde = 10,
                            ValorCusto = 110m,
                            ValorVenda = 449.90m
                        },
                        new
                        {
                            Id = 11,
                            CategoriaId = 7,
                            Descricao = "Headset gamer com som surround 7.1 virtual, drivers de 50mm, microfone com cancelamento de ruído, almofadas em couro respirável.",
                            Destaque = true,
                            Foto = "https://m.media-amazon.com/images/I/61CGHv6kmWL._AC_SX679_.jpg",
                            Nome = "Headset Gamer 7.1",
                            Qtde = 7,
                            ValorCusto = 90m,
                            ValorVenda = 379.90m
                        },
                        new
                        {
                            Id = 12,
                            CategoriaId = 8,
                            Descricao = "Caixa de som portátil Bluetooth 5.3, 30W RMS, graves potentes, resistência à água IPX7, bateria de 12 horas.",
                            Destaque = true,
                            Foto = "https://m.media-amazon.com/images/I/71b8J1fVqOL._AC_SX679_.jpg",
                            Nome = "Caixa de Som Bluetooth",
                            Qtde = 14,
                            ValorCusto = 80m,
                            ValorVenda = 329.90m
                        },
                        new
                        {
                            Id = 13,
                            CategoriaId = 8,
                            Descricao = "Soundbar 2.1 canais com subwoofer wireless, 200W RMS, Bluetooth 5.0, entradas HDMI ARC e óptica, controle remoto incluso.",
                            Destaque = false,
                            Foto = "https://m.media-amazon.com/images/I/61CGHv6kmWL._AC_SX679_.jpg",
                            Nome = "Soundbar 2.1",
                            Qtde = 5,
                            ValorCusto = 200m,
                            ValorVenda = 899.90m
                        },
                        new
                        {
                            Id = 14,
                            CategoriaId = 1,
                            Descricao = "Smartphone premium Samsung com tela Dynamic AMOLED 2X de 6.8 polegadas, processador Snapdragon 8 Gen 3, câmera de 200MP, S-PEN integrada.",
                            Destaque = true,
                            Foto = "https://images.samsung.com/is/image/samsung/p6p-br/galaxy-s24-ultra/bu_s24_ultra_titanium_gray.jpg",
                            Nome = "Galaxy S24 Ultra",
                            Qtde = 7,
                            ValorCusto = 2500m,
                            ValorVenda = 11000.00m
                        },
                        new
                        {
                            Id = 15,
                            CategoriaId = 2,
                            Descricao = "Notebook premium Samsung com tela AMOLED 3K de 16 polegadas, processador Intel Core Ultra 7, 16GB RAM, SSD 512GB.",
                            Destaque = true,
                            Foto = "https://images.samsung.com/is/image/samsung/p6p-br/galaxy-book4-pro/bu_book4_pro_platinum_silver.jpg",
                            Nome = "Galaxy Book4 Pro",
                            Qtde = 2,
                            ValorCusto = 3000m,
                            ValorVenda = 15000.00m
                        },
                        new
                        {
                            Id = 16,
                            CategoriaId = 4,
                            Descricao = "Fones de ouvido True Wireless com cancelamento ativo de ruído adaptativo, som 24-bit Hi-Fi, bateria de 6h + 18h estojo.",
                            Destaque = false,
                            Foto = "https://images.samsung.com/is/image/samsung/p6p-br/galaxy-buds3-pro/bu_buds3_pro_silver.jpg",
                            Nome = "Galaxy Buds3 Pro",
                            Qtde = 10,
                            ValorCusto = 500m,
                            ValorVenda = 2200.00m
                        });
                });

            modelBuilder.Entity("ConectaStore.API.Models.Venda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("ConectaStore.API.Models.ItemVenda", b =>
                {
                    b.HasOne("ConectaStore.API.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConectaStore.API.Models.Venda", "Venda")
                        .WithMany("Itens")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("ConectaStore.API.Models.Produto", b =>
                {
                    b.HasOne("ConectaStore.API.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ConectaStore.API.Models.Venda", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
